eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <label>Contact Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individuals</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Head Office (AA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Branch (AB)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary (AD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correspondent Bank (BA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Bank (BB)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Bank (BC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clearing House (BP)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finance Company (BQ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commodity Broker (BR)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security Broker and Dealer (BS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Broker (BT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Building Society (BV)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance Company (BW)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Financial Institutions (BZ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Limited Company (CA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partnership (CS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Authorities (DC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individuals (EA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minors (EB)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff (EC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sole Trader (ED)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIPs (EJ)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Net Worth Individuals (EE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non Profit Organisations (FA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Masjid (FB)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trust (FC)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Charity (UK) (FD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-operatives (FE)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Club and Associates (FF)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>International_Fund_Transfer_Destination__c</fullName>
        <label>International Fund Transfer Destination</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>International_Fund_Transfer_Frequency__c</fullName>
        <label>International Fund Transfer Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Daily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once a week</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once a month</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once a quarter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once every six months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Once a year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rarely</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Never</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Often</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>International_Fund_Transfer_Source__c</fullName>
        <label>International Fund Transfer Source</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PEP_Associate__c</fullName>
        <label>PEP Associate</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Panoptic_ID__c</fullName>
        <description>C0592</description>
        <label>Panoptic ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Panoptic_Score__c</fullName>
        <description>C0592</description>
        <label>Panoptic Score</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pep__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Please tick this box if the customer is a politically exposed person.</inlineHelpText>
        <label>PEP?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Premier_Status__c</fullName>
        <label>Premier Status</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_of_Wealth__c</fullName>
        <label>Source of Wealth</label>
        <picklist>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gift</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inheritance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organisation Funding Political</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Own Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stocks and Shares</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>What_is_your_total_net_worth__c</fullName>
        <label>What is your total net worth?</label>
        <picklist>
            <picklistValues>
                <fullName>&lt;£500,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>£500,000 - £1,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>£1,000,000 - £5,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>£5,000,000 - £10,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>£10,000,000 – £15,000,000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;£15,000,000</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>required_ebs_id__c</fullName>
        <description>To be used when you need to specify the account number</description>
        <inlineHelpText>To be used when you need to specify the account number</inlineHelpText>
        <label>required ebs id</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/classes/MMR_Data.cls
global class MMR_Data
{
	public class KeyValue
    {
        public string Key{get;set;}
        public string Value{get;set;}
        
        public KeyValue(String keyVal, String val)
        {
            Key = keyVal;
            Value = val;
            
            if(Key == null) Key = '';
        }
    }

	public class KeyValueCountry
    {
        public string Key{get;set;}
        public string Value{get;set;}
        public Boolean IsEU{get;set;}
        
        public KeyValueCountry(String keyVal, String val, Boolean eu)
        {
            Key = keyVal;
            Value = val;
            IsEU = eu;
            
            if(Key == null)Key='';
        }
    }

	global virtual class GenericResponse
    {
        public String URL{get;set;}
        public Boolean Success{get;set;}
        public string Error{get;set;}
    }

	global class HPPDetailsDataResponse extends GenericResponse
    {
        public HPPDetailsData Data {get;set;}
    }

	global class HPPDetailsData 
    {
        public List<PrimaryApplicantData> Applicants{get;set;}
        
        public List<KeyValue> CountriesOfBirth{get;set;}
        public List<KeyValueCountry> Nationality{get;set;}
        public List<KeyValue> RelationshipTo{get;set;}
        public List<KeyValue> RelationshipToYPSA{get;set;}
        public List<KeyValue> Title{get;set;}
        public List<KeyValue> TitleYPSA{get;set;}
        public List<KeyValue> EmploymentType{get;set;}
        public List<KeyValue> EmploymentSector{get;set;}
        public List<KeyValue> VisaType{get;set;}
        public List<KeyValue> ProofID{get;set;}
        public List<KeyValue> MaritalStatus{get;set;}
        public List<KeyValue> Campaigns{get;set;}
        public List<KeyValue> HomeDetails{get;set;}
        public List<KeyValue> SourceOfIncome{get;set;}
        public List<KeyValue> CustomerType{get;set;}
        public List<KeyValue> Contact{get;set;}

		public List<KeyValue> TotalNetWorth{get;set;}
		public List<KeyValue> IntFundsFrequency{get;set;}
		public List<KeyValue> IntFundsSource{get;set;}
		public List<KeyValue> IntFundsDestination{get;set;}
		public List<KeyValue> SourceOfFunds{get;set;}
		public List<KeyValue> SourceOfWealth{get;set;}
		public List<KeyValue> SourceOfFundsCountry{get;set;}
		public List<KeyValue> EstMnthlyVolIn{get;set;}
		public List<KeyValue> EstMnthlyVolOut{get;set;}
		public List<KeyValue> EstMnthlyNumTxIn{get;set;}
		public List<KeyValue> EstMnthlyNumTxOut{get;set;}
		public List<KeyValue> EstCashWthdrwlFreq{get;set;}
		public List<KeyValue> EstCashDepositFreq{get;set;}
		public List<KeyValue> Authorisers{get;set;}

        
        public HPPDetailsData()
        {
            Applicants = new List<PrimaryApplicantData>();
            
            
            HomeDetails = new List<KeyValue>();
            CountriesOfBirth = new List<KeyValue>();
            Nationality= new List<KeyValueCountry>();
            RelationshipTo= new List<KeyValue>();
            RelationshipToYPSA= new List<KeyValue>();
            Title= new List<KeyValue>();
            TitleYPSA= new List<KeyValue>();
            EmploymentType= new List<KeyValue>();
            EmploymentSector= new List<KeyValue>();
            VisaType= new List<KeyValue>();
            ProofID= new List<KeyValue>();
            MaritalStatus = new List<KeyValue>();
            Campaigns = new List<KeyValue>();
            SourceOfIncome = new List<KeyValue>();
            CustomerType = new List<KeyValue>();
            Contact = new List<KeyValue>();

			TotalNetWorth= new List<KeyValue>();
			IntFundsFrequency= new List<KeyValue>();
			IntFundsSource= new List<KeyValue>();
			IntFundsDestination= new List<KeyValue>();
			SourceOfFunds= new List<KeyValue>();
			SourceOfWealth= new List<KeyValue>();
			SourceOfFundsCountry= new List<KeyValue>();
			EstMnthlyVolIn= new List<KeyValue>();
			EstMnthlyVolOut= new List<KeyValue>();
			EstMnthlyNumTxIn= new List<KeyValue>();
			EstMnthlyNumTxOut= new List<KeyValue>();
			EstCashWthdrwlFreq= new List<KeyValue>();
			EstCashDepositFreq= new List<KeyValue>();
			Authorisers= new List<KeyValue>();

        }
    }

	public class PrimaryApplicantData
    {
        public String Id{get;set;}
        
        public String ContactName {get;set;}
		
		public String EBS_ID_c {get;set;}
        public String required_ebs_id_c {get;set;}
        
        public String Valid{get;set;}
        
        public Boolean Possible_Duplicate_c{get;set;}
        public String Customer_Type_c {get;set;}
        public String Premier_Status_c{get;set;}
        public String Correct {get;set;}


		public String Panoptic_ID_c {get;set;}
		public String Panoptic_Score_c {get;set;}
		// public String VIP_c {get;set;} // No longer required but left to use as customer type if required 
		public String PEP_c {get;set;} 
		public String PEP_Associate_c {get;set;}		
		public String What_is_your_total_net_worth_c {get;set;}
		public String International_Fund_Transfer_Frequency_c {get;set;}
		public String International_Fund_Transfer_Source_c {get;set;}
		public String International_Fund_Transfer_Destination_c {get;set;}
		public String Source_of_Wealth_c {get;set;}
		public String Source_of_Funds_c {get;set;}
		public String Source_of_Funds_Country_c {get;set;}
		public String Estimated_Monthly_Volume_Inward_c {get;set;}
		public String Est_Monthly_Num_of_Transactions_Inward_c {get;set;}
		public String Estimated_Monthly_Volume_Outward_c {get;set;}
		public String Est_Monthly_Num_of_Transactions_Outward_c {get;set;}
		public String Estimated_Cash_Withdrawal_Frequency_c {get;set;}
		public String Estimated_Cash_Deposit_frequency_c {get;set;}


        public String DecryptedId
        {
            get{
                return CAA_Helper.DecryptData(Id);
            }
        }
        
        public PrimaryApplicantData(Account acc)
        {
            
            Id = acc.id;
            
              
            if(!CAA_Helper.IsGuestUser())
            {
                Customer_Type_c = acc.Customer_Type__c;
                Premier_Status_c = acc.Premier_Status__c; 
                required_ebs_id_c = acc.required_ebs_id__c;
            } 
			
			ContactName=acc.Contact_Name__c;
                
            
			Panoptic_ID_c=acc.Panoptic_ID__c;
			Panoptic_Score_c=acc.Panoptic_Score__c;
			 // VIP_c=acc.VIP__c; // No longer required but left to use as customer type if required 
			PEP_c= acc.PEP__c == null ? 'null' :acc.PEP__c ? 'true' : 'false' ; 
			PEP_Associate_c=acc.PEP_Associate__c; 			
			What_is_your_total_net_worth_c=acc.What_is_your_total_net_worth__c;
			International_Fund_Transfer_Frequency_c=acc.International_Fund_Transfer_Frequency__c;
			International_Fund_Transfer_Source_c=acc.International_Fund_Transfer_Source__c;
			International_Fund_Transfer_Destination_c=acc.International_Fund_Transfer_Destination__c;
			Source_of_Wealth_c=acc.Source_of_Wealth__c;
			Source_of_Funds_c=acc.Source_of_Funds__c;
			Source_of_Funds_Country_c=acc.Source_of_Funds_Country__c;
			Estimated_Monthly_Volume_Inward_c=acc.Estimated_Monthly_Volume_Inward__c;
			Est_Monthly_Num_of_Transactions_Inward_c=acc.Est_Monthly_Num_of_Transactions_Inward__c;
			Estimated_Monthly_Volume_Outward_c=acc.Estimated_Monthly_Volume_Outward__c;
			Est_Monthly_Num_of_Transactions_Outward_c=acc.Est_Monthly_Num_of_Transactions_Outward__c;
			Estimated_Cash_Withdrawal_Frequency_c=acc.Estimated_Cash_Withdrawal_Frequency__c;
			Estimated_Cash_Deposit_frequency_c=acc.Estimated_Cash_Deposit_frequency__c;
            
        }

        public Account UpdateAccount(Account acc)
        {
            PrimaryApplicantData data = this;
            acc.Panoptic_ID__c=data.Panoptic_ID_c;
			acc.Panoptic_Score__c=data.Panoptic_Score_c;
			// acc.VIP__c=data.VIP_c; // No longer required but left to use as customer type if required 
			acc.Pep__c =  data.PEP_c == 'true'; 
			acc.PEP_Associate__c=data.PEP_Associate_c;
			acc.What_is_your_total_net_worth__c=data.What_is_your_total_net_worth_c;
			acc.International_Fund_Transfer_Frequency__c=data.International_Fund_Transfer_Frequency_c;
			acc.International_Fund_Transfer_Source__c=data.International_Fund_Transfer_Source_c;
			acc.International_Fund_Transfer_Destination__c=data.International_Fund_Transfer_Destination_c;
			acc.Source_of_Wealth__c=data.Source_of_Wealth_c;
			acc.Source_of_Funds__c=data.Source_of_Funds_c;
			acc.Source_of_Funds_Country__c=data.Source_of_Funds_Country_c;
			acc.Estimated_Monthly_Volume_Inward__c=data.Estimated_Monthly_Volume_Inward_c;
			acc.Est_Monthly_Num_of_Transactions_Inward__c=data.Est_Monthly_Num_of_Transactions_Inward_c;
			acc.Estimated_Monthly_Volume_Outward__c=data.Estimated_Monthly_Volume_Outward_c;
			acc.Est_Monthly_Num_of_Transactions_Outward__c=data.Est_Monthly_Num_of_Transactions_Outward_c;
			acc.Estimated_Cash_Withdrawal_Frequency__c=data.Estimated_Cash_Withdrawal_Frequency_c;
			acc.Estimated_Cash_Deposit_frequency__c=data.Estimated_Cash_Deposit_frequency_c;
            
            return acc;      
        }
    }

	global class HPPDetailsCompleteData
    {
        public List<PrimaryApplicantData> Applicants{get;set;}
        public String EventLogId{get;set;}
		public String ApprovalUser{get;set;}
		public Boolean isEDD {get;set;}   // Indicates that an internal staff member completed Adhoc EDD questions
    }
}