eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Are_you_happy_for_IBB_to_hold_your_data__c</fullName>
        <description>Confirms if the bank can hold the customers data</description>
        <label>Are you happy for us to hold your data?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EBS_ID__c</fullName>
        <externalId>true</externalId>
        <label>EBS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Marketing_Preference__c</fullName>
        <inlineHelpText>For use with new Marketing preference code.</inlineHelpText>
        <label>Marketing Preference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nature_of_Business_NPAA__c</fullName>
        <description>For use with NPAA build</description>
        <label>Nature of Business NPAA</label>
        <picklist>
            <picklistValues>
                <fullName>Accounting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advertising,Public Relations and Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aerospace and Defence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Architecture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Automotive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aviation and Airlines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biotechnology</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clergy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction and Installation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consulting Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delivery</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy and Utilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilities, Maintenance and Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fire, Law Enforcement and Security</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food,Beverage and Tobacco</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government and Local Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare - Administrative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare - Nursing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare - Practitioners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Healthcare - Technicians</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Holding and Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hotel,Gaming,Leisure and Travel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internet and New Media</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT- All</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT - Computers, Hardware</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Web_Form_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Form Data</label>
        <referenceTo>Web_Form_Data__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Business_Account</fullName>
        <active>true</active>
        <label>Business Account</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Prospect_Customer__c</fullName>
        <label>Prospect/Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Dummy_Account__c.object
<CustomObject>
    <fields>
        <fullName>Date_Of_Birth__c</fullName>
        <label>Date Of Birth</label>
        <type>Date</type>
    </fields>
    <label>Dummy Account</label>
    <nameField>
        <label>Dummy Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dummy Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/EventLog__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EventLog</label>
    <nameField>
        <label>EventLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/HPP_extended_opportunity__c.object
<CustomObject>
    <fields>
        <fullName>EmailAddressHPPCAAComms__c</fullName>
        <description>Email address populated by workflow to show email address for customer communication.</description>
        <label>EmailAddressHPPCAAComms</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>HPP extended opportunities</relationshipLabel>
        <relationshipName>HPP_extended_opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HPP extended opportunity</label>
    <nameField>
        <displayFormat>HPPEO{0000}</displayFormat>
        <label>HPP extended opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HPP extended opportunities</pluralLabel>
    <recordTypes>
        <fullName>CPF</fullName>
        <active>true</active>
        <description>For use with CPF</description>
        <label>CPF</label>
    </recordTypes>
    <recordTypes>
        <fullName>HPP_CAA</fullName>
        <active>true</active>
        <description>For use with HPP CAA</description>
        <label>HPP CAA</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/IBB_Product_Set__c.object
<CustomObject>
    <fields>
        <fullName>IDD_Document__c</fullName>
        <label>IDD Document</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDD_NonF2F_Document__c</fullName>
        <description>MMR IDD</description>
        <label>IDD NonF2F Document</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy to let</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductSetType__c</fullName>
        <label>Product Set Type</label>
        <picklist>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HTB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CDM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Set</label>
    <nameField>
        <label>Product Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sets</pluralLabel>
    <recordTypes>
        <fullName>HPP</fullName>
        <active>true</active>
        <description>For use with HPP eligibility</description>
        <label>HPP</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HPP_extended_opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HPP extended opportunity</label>
        <referenceTo>HPP_extended_opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Intermediary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Intermediary Contact</label>
        <referenceTo>Business_Contacts__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_People_Applying__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Number of People Applying</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Web_Form_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Form Data</label>
        <referenceTo>Web_Form_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Were_you_aware_of_the_procuration_fee__c</fullName>
        <label>Were you aware of the procuration fee</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>HPP_CAA</fullName>
        <active>true</active>
        <businessProcess>HPP CAA</businessProcess>
        <description>For use with HPP CAA Build October 2012</description>
        <label>HPP CAA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/objects/PostCode__c.object
<CustomObject>
    <description>Poscode lookup for seller</description>
    <fields>
        <fullName>PostCode__c</fullName>
        <label>PostCode</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>PostCode</label>
    <nameField>
        <label>PostCode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PostCodes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AIP_Allowed__c</fullName>
        <label>AIP Allowed?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Document PPDG/src/objects/Web_Form_Data__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EBS_ID__c</fullName>
        <label>EBS ID</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <label>Web Form Data</label>
    <nameField>
        <displayFormat>WForm-{00000}</displayFormat>
        <label>Web Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Form Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/classes/MMR_EligibilityController.cls
/* ------------------------------------------------------------------------------------	*/
/* C0586																				*/
/* ------------------------------------------------------------------------------------	*/

public without sharing class  MMR_EligibilityController 
{
	public Boolean displayIncomeAssisted {get ; set ;}	// C0586

    public Integer NumApplying{get;set;}
        public String GetIDDDocument(String type,Boolean faceToFace)
    {
        for(IBB_Product_Set__c p : GetProductSets)
        {
            if(p.ProductSetType__c.equalsIgnoreCase(type))
            {
                if(faceToFace)
                return LiabilitiesHelperFunctions.GetResourceURL( p.IDD_Document__c);
                
                return LiabilitiesHelperFunctions.GetResourceURL( p.IDD_NonF2F_Document__c);
            }            
        }
        return null;
    }
    
     Transient List<IBB_Product_Set__c> ProductSets;
    
    public List<IBB_Product_Set__c> GetProductSets
    {
        get{
            if(ProductSets== null)
            {
                ProductSets = [select id,name,IDD_Document__c,IDD_NonF2F_Document__c ,ProductSetType__c  from ibb_product_set__c  where ProductSetType__c != null ];
            }
            return ProductSets;
        }
    }
    
    
    public String HPPDocument{
        get{
            return GetIDDDocument('HPP',true);
        }
    }
    public String HPSDocument{
        get{
            return GetIDDDocument('HPS',true);
        }
    }
    public String PremierDocument{
        get{
            return GetIDDDocument('Premier',true);
        }
    }
    public String BTLDocument{
        get{
            return GetIDDDocument('BTL',true);
        }
    }
    
    public String HPPDocumentNon{
        get{
            return GetIDDDocument('HPP',false);
        }
    }
    public String HPSDocumentNon{
        get{
            return GetIDDDocument('HPS',false);
        }
    }
    public String PremierDocumentNon{
        get{
            return GetIDDDocument('Premier',false);
        }
    }
    public String BTLDocumentNon{
        get{
            return GetIDDDocument('BTL',false);
        }
    }
    
    


    public String EligibleOutput { get; set; }
    public String FirstName{get;set;}
    public String Surname{get;set;}
    public String Title{get;set;}
    public HPP_extended_opportunity__c exOpp{get;set;}
    public Applicant__c Applicant{get;set;}
    public Boolean WasAccountFound{get;set;}
    public List<Account> AccountsFound{get;set;}
    public Event Meeting{get;set;}
    public Boolean IsExternal {get;set;}
	public Boolean IsBTL_LTD { get; set;}
	public Boolean IsBTL { get; set;}
    
    public boolean AllowAIP{get;set;}

    public String msg{
    get{
        String html = '<ul>';
    
        for(ApexPages.Message m : ApexPages.getMessages())
        {
            html += '<li>' + m.getSummary() +  '</li>';
        }
        
        html += '</ul>';
        
        return html;
    }
    }

    public RecordType recType {
        get {
            if (recType == null){            
                recType = [select id from recordType where ispersontype=true and sobjectType='account' and DeveloperName = 'ProspectCustomer' limit 1];
            }
            return recType;
        }
        set;
    }
    
    public RecordType recTypeExternal {
        get {
            if (recTypeExternal == null){            
                recTypeExternal = [select id from recordType where ispersontype=true and sobjectType='account' and DeveloperName = 'HPP_CAA_External' limit 1];
            }
            return recTypeExternal ;
        }
        set;
    }
    
	// C0644
	public RecordType recTypeBusiness {
        get {
            if (recTypeBusiness == null){            
                recTypeBusiness = [select id from recordType where ispersontype=false and sobjectType='account' and DeveloperName = 'Business_Account' limit 1];
            }
            return recTypeBusiness ;
        }
        set;
    }
    
    
    
    
     public RecordType oppRecType {
        get {
            if (oppRecType == null){            
                  oppRecType = [select id from recordType where  sobjectType='opportunity' and DeveloperName = 'HPP_CAA' limit 1];
            }
            return oppRecType ;
        }
        set;
    }
    
  public boolean IsFirstPage {get;set;}

  
  public Postcode__c Bdm{get;set;} 
  public String BdmLink{get;set;}
  public String BdmName{get;set;}
  public String RoundRobinUserId {get;set;}
  
  
  
    public MMR_EligibilityController () {
        NumApplying = 1;
        IsFirstPage = true;
    
       Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=edge');
        List<USer> usr = [select name, AIP_Allowed__c from user where id=:   UserInfo.getUserId() ];
         AllowAIP = usr[0]. AIP_Allowed__c == 'Yes' ;
        IsExternal = false;
       
   
        ShowAppointment = false;
        MeetingDate = new Dummy_Account__c();
        MeetingDate.Date_Of_Birth__c = Date.today();
        Meeting = new Event();
        AccountsFound = new List<Account>();
        system.debug('CTOR');
        Applicant = new Applicant__c();
        exOpp = new HPP_extended_opportunity__c ();
        if(existingSFDCCustomerId != null)
        {
            Applicant1  = DataHelper.GetAccount(existingSFDCCustomerId)[0];
			system.debug('Applicant1 found during constructor:'+Applicant1);
            Applicant = new Applicant__c();
            FirstName = Applicant1.FirstName;
            Surname= Applicant1.LastName;
            Title=Applicant1.Salutation;
			Apexpages.currentPage().getParameters().put('ExistingAccountId', existingSFDCCustomerId);
           
        }   

		IsFirstPage = true;
   }


   // public Integer NoApps{get;set;}

    public Account Applicant1{get;set;}
    public Account Applicant2{get;set;}
    public Account Applicant3{get;set;}
    public Account Applicant4{get;set;}
	public Account Applicant5{get;set;} // C0644 Fifth applicant is 4th Director
           
    public void ProcessCheckBox()
    {   
    Applicant1.marketing_preference__C = '';
   
    if(!HasMail)
        Applicant1.marketing_preference__C += 'mail ';
        
    if(!HasEmail)
        Applicant1.marketing_preference__C += 'email ';

    if(!HasPhone)
        Applicant1.marketing_preference__C += 'phone ';  

    if(!HasSMS)
        Applicant1.marketing_preference__C += 'sms '; 
    }   
   
    public void EmailError()
    {
          String msg = 'Please enter an email address.'  ;
          ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, msg);
          ApexPages.addMessage(myMsg);
    }
   
    public PageReference check()
    {
        Boolean isEligible = false;
    
        EligibleOutput = '';
		WasAccountFound = false;
    
		if(Applicant1.Are_you_happy_for_IBB_to_hold_your_data__c != 'Yes')
		{
			String msg = 'You have indicated that you are not happy for IBB to store your information.';
			  ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, msg);
			  ApexPages.addMessage(myMsg);
			  return null;
		}

		if(Opp.Intermediary_Contact__c!=null && Opp.Were_you_aware_of_the_procuration_fee__c==null) // C0694
		{
			String msg = 'Please answer the question \"Were you aware that the intermediary will receive a procuration fee if this deal completes?\" under \"Marketing Information\" before continuing.';
			  ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.INFO, msg);
			  ApexPages.addMessage(myMsg);
			  return null;
		}

		if(IsBTL_LTD && !('Holding and maintenance'.equalsIgnoreCase(Applicant1.Nature_of_Business_NPAA__c)))
		{
			String msg = 'The nature of this business is not compatible with this product.';
			  ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, msg);
			  ApexPages.addMessage(myMsg);
			  return null;
		}
    
		System.debug('IS BTL LTD = '+IsBTL_LTD);
		System.debug('Applicant1 RecType='+Applicant1.RecordTypeID);
		System.debug('Applicant1 FirstNAme='+Applicant1.FirstName);
		System.debug('Applicant1 LastName='+Applicant1.LastName);
		System.debug('Applicant1 Title='+Applicant1.Salutation);
		
		
		EligibleOutput  = '';
		if(!IsBTL_LTD)
		{
			Applicant1.FirstName = FirstName;
			Applicant1.LastName= Surname;
			Applicant1.Salutation = Title;
		}
    
    
    
    
    
    ProcessCheckBox();
    
    if(!HasEmail  )
    {
        if(Applicant1.PersonEmail == null && !IsBTL_LTD)
        {
            EmailError();
            return null;
        }
        
        if(Applicant1.PersonEmail == '' && !IsBTL_LTD)
        {
            EmailError();
            return null;
        }
    }
    
    
    if(!IsExternal)
    {
		List<Account> accs = [select id, lastname,firstname,EBS_ID__c,Date_of_Birth__c, name  from account where lastname=:Applicant1.lastname and firstname=:Applicant1.firstname and Date_of_Birth__c =: Applicant1.Date_of_Birth__c   ];
    
		AccountsFound = new List<Account>();
    
		for(Account a : accs)
		{
			if(a.id != Applicant1.id)
			{
				WasAccountFound = true;
				String msg = 'Combination of first name, last name and data of birth already exist.  Id : ' + a.id ;
				ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, msg);
				ApexPages.addMessage(myMsg);
				AccountsFound.add(a); 
			}
		}
    
    
		if(AccountsFound.size() > 0 )
		{
			WasAccountFound = true;  
			return null;      
		}
    }
    
    
    
    boolean isNew = Applicant1.id == null;
    
    upsert Applicant1  ;
    Opp.AccountId = Applicant1.id; 
    
    if(isNew)
    {
        Applicant1 = DataHelper.GetAccount(Applicant1.id )[0];
    }
    
    
    
    
    //Opp.Number_of_People_Applying__c= NoApps;
    Opp.Stagename ='Awaiting Assessment';
    Opp.closedate = datetime.now().date();
    Opp.Web_Form_Data__c = webFormDataId;
    upsert Opp;
    
    if(Applicant.id == null)
    {
    Applicant.Opportunity__c= Opp.id;
    Applicant.Prospect_Customer__c = Applicant1.id;
    Applicant.Applicant_Number__c = 1;
    upsert Applicant;
    }
    
    if(exOpp.Opportunity__c== null)
    {
        exOpp.Opportunity__c = Opp.Id;
    }

    exOpp.EmailAddressHPPCAAComms__c = Applicant1.PersonEmail; // C00099
    upsert exOpp;
    Opp.HPP_extended_opportunity__c = exOpp.id;
    
    List<String> reasons = LiabilitiesHelperFunctions.IsEligible(Applicant1,Opp,Applicant2,Applicant3,Applicant4);
    
    system.debug('reasons');
    system.debug(reasons);
    
    String reason='';
    
    for(String r : reasons)
    {
        reason += r + '\n';
    }
    
    IBB_Product_Set__c productSet = [select id from IBB_Product_Set__c where name=:Opp.Interested_in__c  ];
    
    String directorId;
    if(IsExternal)
    {
        directorId = EventHelper.GetExternalDirectorIdByProductSet(productSet .id);
    }
    else
    {
        directorId = EventHelper.GetDirectorIdByProductSet(productSet .id);
    }
   
       
    
    Opp.ProductEventDirector__c = directorId ;
    
    /* C0586
	if(reasons[0] == 'YES')
	*/
	Opp.Income_Assisted_Application__c = false ;
	if(reasons[0] == 'YES' || 
		(!IsBTL_LTD && reasons [0] == 'The information you have submitted indicates that the monthly rental income is not sufficient.'
		 && reasons .size() == 1 )) // C0586 & C0644 add in Ltd Co. check as IAA is not valid
    {       
		/* C0586 */
		if (reasons [0] == 'The information you have submitted indicates that the monthly rental income is not sufficient.')
		{
			displayIncomeAssisted = true;
			EligibleOutput  = 'Applicant is Eligible - Proceed as an Income Assisted Application';
			Opp.Income_Assisted_Application__c = true ;
		}
		else 
		{
			displayIncomeAssisted = false;
			EligibleOutput  = 'Applicant is Eligible';

		}
		/* C0586 end */

		// C0586 EligibleOutput  = 'Applicant is Eligible';	
		Opp.StageName = 'HPP -Eligible Opportunity';
    
    
		try    
		{
			 update Opp;
		}
		catch(Exception ex)
		{
			return null;
		}
    
   
    
		isEligible =true;

    
		//Set up appointment
    
		system.debug('IsExternal : ' + IsExternal );
		system.debug('PostCode : ' + Applicant1.BillingPostalCode);
    
		Postcode__c Bdm;
    
		if(!IsExternal )
			Bdm = FunctionHelper.GetPostcodeSeller(Applicant1.BillingPostalCode);   
    
		system.debug('Bdm after postcode lookup :' + Bdm);
    
		String userId;
    
		  system.debug('bdm ' + bdm);
    
    
		if(Bdm != null)
		{
			if(Bdm.user__c != null)
			{
				userId = Bdm.user__c;
			}
			else
			{
				if(RoundRobinUserId == null)
				{
					RoundRobinUserId = FunctionHelper.GetRoundRobinUserId();                
				}
				userId = RoundRobinUserId;
			}
		}
		else
		{
			if(RoundRobinUserId == null)
			{
				RoundRobinUserId = FunctionHelper.GetRoundRobinUserId();
			}
			userId = RoundRobinUserId;
		}
    
       if(Opp.Seller__c == null)
            Opp.Seller__c = userId;
    
        system.debug('BDM id :' + userId );
        
        List<User> usr = [select name from User where id=: userId  limit 1];
        if(usr.size() > 0)
        {
            BdmName= usr[0].name;
        }
        
        Integer month= Date.today().month() - 1;
        Integer year= Date.today().year();        
        
        BdmLink = '/00U/c?cType=1&cal_lkid='+ userid +'&md0=' + year +'&md1=' + month;
        
       
        Meeting.Subject = 'New ' + Opp.Interested_in__c;
       update opp;
   
    
    
    }
    else
    {
		Opp.Reason_for_ineligible_referral__c = reason;
		Opp.StageName = 'Not Eligible - HPP';

		try
		{
			update Opp;
		}
		catch(Exception ex)
		{
			return null;
		}
    
		EligibleOutput  = '<ul>';
    
			for(Integer i = 0; i< reasons.size();i++)
			{
				EligibleOutput += '<li>' + reasons[i] + '</li>';
			}
			EligibleOutput  += '</ul>';
	}
    
    
	if(isEligible && IsExternal )
	{
		return ExternalAIP();
	}
    
    return null;
 }
    
    public string EventId{get;set;}
    
   public Boolean IsChecked(String value)
    {
        if(value == null)
            return false;
            
        if(value.toLowerCase() == 'on')
            return true;
            
        return false;
    
    }
    
    public PageReference Setup()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        IsExternal = false;
		IsBTL_LTD=false;
		IsBTL = false;  
        if(Applicant1 == null)
        {
			system.debug('Applicant1 not found during setup:');
			Applicant1 = new Account(RecordTypeId = recType.Id, FirstName='', LastName='', Salutation = '');     
        }
		else
		{
			system.debug('Applicant1 found during setup:'+Applicant1);
		}
    
        Opp = new Opportunity(RecordType = oppRecType); 
        Opp.RecordTypeId = oppRecType.id;
        Opp.Name= 'HPP CAA - ' + Applicant1.name ;   
        Opp.Stagename ='Awaiting Assessment';
        Opp.closedate = datetime.now().date();
        Opp.Number_of_People_Applying__c = 1;
        
        opp.CustomerEmailRequired__c = true;    // C00099
        
        Applicant__c app = new Applicant__c ();
        app.Prospect_Customer__c= Applicant1 .id;
        app.Applicant_Number__c = 1;
        app.Primary_Account_Holder__c = true;            
		return null;
    }
    
    private Campaign externalCampaign {
        get {
            if (externalCampaign == null) {
                if (String.isNotBlank(Opp.Name)) {
                    List<Campaign> campaigns = new List<Campaign>();
                    
                    if (Opp.Name.contains('Home Purchase Plan')) {
                        campaigns = [
                            SELECT Name
                            FROM Campaign
                            WHERE Name = 'HPP - Website enquiry (HPB1WEB)'
                            LIMIT 1
                        ];
                    }
                    else if (Opp.Name.contains('Buy to Let')) {
                        campaigns = [
                            SELECT Name
                            FROM Campaign
                            WHERE Name = 'HPP - Website enquiry (HPB1WEB)'
                            LIMIT 1
                        ];
                    }
                    
                    if (!campaigns.isEmpty()) {
                        externalCampaign = campaigns.get(0);
                    }
                }
            }
            else {
                externalCampaign = null;
            }
            
            return externalCampaign;
        }
        set;
    }
    
     public PageReference SetupExternal()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        IsExternal = true;
        if(Applicant1 == null)
        {
            Applicant1 = new Account(RecordTypeId = recTypeExternal.Id, FirstName='', LastName='');     
        }
    
        Opp = new Opportunity(RecordType = oppRecType); 
        Opp.RecordTypeId = oppRecType.id;
        Opp.Name= 'HPP CAA - ' + Applicant1.name ;   
        Opp.Stagename ='Awaiting Assessment';
        Opp.closedate = datetime.now().date();
        Opp.Number_of_People_Applying__c = 1;
        
        if (externalCampaign != null) {
            Opp.CampaignId =  externalCampaign.Id;
        }
        
        Applicant__c app = new Applicant__c ();
        app.Prospect_Customer__c= Applicant1 .id;
        app.Applicant_Number__c = 1;
        app.Primary_Account_Holder__c = true;
                    
        return null;
    }
    
    public Id webFormDataId{get;set;}

    public PageReference ChangeNumApps()
    {      
        IBB_Product_Set__c prodSet = [select id,Max_No_of_Applicants__c, ShortProductType__c,ProductSetType__c  from IBB_Product_Set__c where name = :opp.interested_in__c limit 1 ];
        
        if(Opp.Number_of_People_Applying__c > prodSet.Max_No_of_Applicants__c  )
        {
         
            String msg = 'Only ' + prodSet.Max_No_of_Applicants__c +' applicants allowed for ' + opp.interested_in__c  ;
               ApexPages.Message myMsg = new ApexPages.Message(ApexPages.severity.FATAL, msg);
             ApexPages.addMessage(myMsg);  
            return null;
        }
        
		if(prodSet.ShortProductType__c=='BTLLC')
		{
			IsBTL_LTD=true;
			if(String.isBlank(existingSFDCCustomerId))
			{
				Applicant1 = new Account(RecordTypeId = recTypeBusiness.Id, Organisation_Type__c='Limited Company', Customer_Type__c='Limited Company');
			}
        }

		if(prodSet.ProductSetType__c=='BTL')
		{
			IsBTL=true;
		}

        
        
        // C0644 Ltd Companies can have 5 applicants (Co. + 4 Dir's)
		if(IsBTL_LTD)
		{
			if(String.isBlank(existingSFDCCustomerId))
			{
				if(Opp.Number_of_People_Applying__c> 0)
					Applicant2 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');
           
				if(Opp.Number_of_People_Applying__c> 1)
					Applicant3 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');
           
				if(Opp.Number_of_People_Applying__c> 2)
					Applicant4 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');

				if(Opp.Number_of_People_Applying__c> 3)
					Applicant5 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');
			}
			else
			{
				// New method to create applicants based on existing customer's CPF relationships (Directors)
				if(IsFirstPage)
				{
					getExistingDirectors();
				}

			}

		}
		else
		{
			if(Opp.Number_of_People_Applying__c> 1)
			Applicant2 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');
           
             if(Opp.Number_of_People_Applying__c> 2)
			Applicant3 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');
           
             if(Opp.Number_of_People_Applying__c> 3)
			Applicant4 = new Account(RecordTypeId = recType.Id, FirstName='New', LastName='Account');
		}

		IsFirstPage =false;

        
        webFormDataId = Apexpages.currentPage().getParameters().get('webFormDataId');
       return null;        
    }
    
     public String existingSFDCCustomerId {
        get {
            if (existingSFDCCustomerId == null && !IsExternal){
                existingSFDCCustomerId = ApexPages.currentPage().getParameters().get('ExistingAccountId');
            }
            return existingSFDCCustomerId;
        }
        set;
    }    
    
    public Opportunity Opp{get;set;}
     
     
    public void CompleteEvent()
    {
        IBBEvents ibbEvent = new IBBEvents(Opp.ProductEventDirector__c );
        ibbEvent.CreateFirstEvent(opp.id);
        Completed = true;
    } 
    public boolean Completed{get;set;}   
    public PageReference CompleteAIP()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        CompleteEvent();        
        return null;
    }
    
    public PageReference ExternalAIP()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        CompleteEvent();
        EventLog__c ev = [select id from EventLog__c where opportunity__c = :opp.id limit 1];
        EventId = ev.id;   
      
            return new PageReference('/apex/External_Eligible');   
    }
    
    public PageReference AIP()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        CompleteEvent();
        EventLog__c ev = [select id from EventLog__c where opportunity__c = :opp.id limit 1];
        EventId = ev.id;   
      
            return new PageReference('/apex/HPPEventRedirect?oppid='  + opp.id);  
 
    }
    
    public Boolean ContainsOption(String option)
    {
        return Applicant1 .marketing_preference__C.containsIgnoreCase(option);
    }
    
    public void SetUpBoxes()
    {  

    
    
        if( Applicant1 .marketing_preference__C == null)
            return;
        HasEmail = !ContainsOption('email');
        HasMail= !ContainsOption('mail');
        HasPhone= !ContainsOption('phone');
        HasSMS= !ContainsOption('sms');
        
    }
    
    public Boolean HasEmail{get;set;}
    public Boolean HasMail{get;set;}
    public Boolean HasPhone{get;set;}
    public Boolean HasSMS{get;set;}
    public Boolean HasNone{get;set;}
    
    
    public Dummy_Account__c MeetingDate{get;set;}
    
    
    
    public String OptionTime{get;set;}
    public String OptionEndTime{get;set;}
    
     public List<SelectOption> OptionTimes {
        get {
            if (OptionTimes == null) {
                DateTime DT_TM1 = DateTime.newInstance(Date.Today(), Time.newInstance(7,0,0,0));
                DateTime DT_TM2 = DT_TM1;
                DateTime DT_TM3 = DateTime.newInstance(Date.Today(), Time.newInstance(19,0,0,0));
                 
                OptionTimes = new List<SelectOption>();
                while (DT_TM1.isSameDay(DT_TM2) && (DT_TM1  <= DT_TM3) ) {
                    String strTM = DT_TM1.Format('h:mm a');
                    OptionTimes.add(new SelectOption(strTM,strTM));
                    DT_TM1 = DT_TM1.addMinutes(30);
                }
            }
            return OptionTimes;
        }
        private set;
    }
    
    public PageReference DoNothing ()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        system.debug('action date: ' +OptionTime );
        return null;
    }
    
    public boolean ShowAppointment {get;set;}
    
    public PageReference BookAppointment()
    {
        LiabilitiesHelperFunctions.SetPageHeader();    
        Meeting.ActivityDateTime = DateTime.newInstance(MeetingDate.Date_Of_Birth__c,ParseTime(OptionTime));

        return null;
    }
    
    private Time ParseTime(String strTime) {
        Integer TM_H;
        Integer TM_M;
        String TM_AP;
        String[] tmp;
 
        tmp = strTime.split(':', 2);
        TM_H = Integer.valueOf(tmp[0]);
         
        tmp = tmp[1].split(' ', 2);
        TM_M = Integer.valueOf(tmp[0]);
        TM_AP = tmp[1];
        return Time.newInstance(TM_H + (TM_AP.startsWith('P') ? 12 : 0), TM_M, 0, 0);
    }
    
    public List<SelectOption> OptionEndTimes {
        get {
                if(OptionTime == null)
                {
                  OptionTime =  DateTime.newInstance(Date.Today(), Time.newInstance(7,0,0,0)).Format('h:mm a');
                }         
           
                DateTime DT_TM1 =    DateTime.newInstance(Date.Today(),ParseTime(OptionTime)).addMinutes(30);
                DateTime DT_TM2 = DT_TM1;
                DateTime DT_TM3 = DateTime.newInstance(Date.Today(), Time.newInstance(19,0,0,0));
                 
                OptionTimes = new List<SelectOption>();
                while (DT_TM1.isSameDay(DT_TM2) && (DT_TM1  <= DT_TM3) ) {
                    String strTM = DT_TM1.Format('h:mm a');
                    OptionTimes.add(new SelectOption(strTM,strTM));
                    DT_TM1 = DT_TM1.addMinutes(30);
                }
            
            
            return OptionTimes;
            }
        
        private set;
    }

	private void getExistingDirectors()
	{
		// Get list of CPF relationships based on Applicant1
		List<CPF_Relationship__c> dirs = [select id,Child_Account__c,Shareholder_Percentage__c,Is_Director__c,Is_Shareholder__c,Position_Held__c from CPF_Relationship__c where Parent_Account__c=:Applicant1.id order by CreatedDate];
		
		// Get required data from above list to create each Applicant
		Integer i = 1;
		
		Opp.Number_of_People_Applying__c = dirs.Size();

		for(CPF_Relationship__c dir : dirs)
		{
			Account app = DataHelper.GetAccount(dir.Child_Account__c)[0];
			//app.Is_Director__c = dir.Is_Director__c;
			//app.Is_Shareholder__c = dir.Is_Shareholder__c;
			//app.Is_Signatory__c = dir.Is_Signatory__c;
			//app.Shareholder_Percentage__c = dir.Shareholder_Percentage__c;
			app.Position_Held__c = dir.Position_Held__c;
			if(i==1)
			{
				Applicant2 = app;
			}
			else if(i==2)
			{
				Applicant3 = app;
			}
			else if(i==3)
			{
				Applicant4 = app;
			}
			else if(i==4)
			{
				Applicant5 = app;
			}
			i++;
		}
	}

    
}