eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/EventLog__c.object
<CustomObject>
    <fields>
        <fullName>EventStatus__c</fullName>
        <label>EventStatus</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EventLog</label>
    <nameField>
        <label>EventLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/HPP_extended_opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>HPP extended opportunities</relationshipLabel>
        <relationshipName>HPP_extended_opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HPP extended opportunity</label>
    <nameField>
        <displayFormat>HPPEO{0000}</displayFormat>
        <label>HPP extended opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HPP extended opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/IBB_Product_Set__c.object
<CustomObject>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy to let</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product Set</label>
    <nameField>
        <label>Product Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HPP_extended_opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HPP extended opportunity</label>
        <referenceTo>HPP_extended_opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>Home Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTL Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Plan Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP BTL (future)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premier Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFA/Wealth Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discretionary Portfolio Service (DPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy-to-Let (BTL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy To Let (Rent Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan Scotland</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ProductEventDirector__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ProductEventDirector</label>
        <referenceTo>ProductEventDirector__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/ProductEventDirector__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>ProductEventDirector</relationshipLabel>
        <relationshipName>ProductEventDirector</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ProductEventDirector</label>
    <nameField>
        <label>ProductEventDirector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ProductEventDirector</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Document PPDG/src/objects/SOQLQuery__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>SOQLQuery</label>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/classes/zTest_MMR_FF_Income.cls
@IsTest
public class zTest_MMR_FF_Income
{
    public ProductEventDirector__c director{get;set;}
     public Event__c event{get;set;} 
     public Opportunity Opp{get;set;}  
     public EventLog__c Log{get;set;} 
     public Attachment att{get;set;}
     public HPP_extended_opportunity__c ex{get;set;} 
     z_ProductHelper pHelp ;

    static testmethod void SetupTest()
    {
         zTest_MMR_FF_Income testable = new zTest_MMR_FF_Income();
        testable.SetUpObjects();    

        PageReference pageRef = Page.MMR_FF_Income;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', testable.log.id);
          
        MMR_FF_Income ctl = new MMR_FF_Income();
        ctl.setup();
    
    }
    
    static testmethod void SaveTest()
    {
         zTest_MMR_FF_Income testable = new zTest_MMR_FF_Income();
        testable.SetUpObjects();    

        PageReference pageRef = Page.MMR_FF_Income;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', testable.log.id);
          
        MMR_FF_Income ctl = new MMR_FF_Income();
        ctl.setup();
        ctl.Save();
    }
    
    static testmethod void SaveData_Test()
    {
         zTest_MMR_FF_Income testable = new zTest_MMR_FF_Income();
        testable.SetUpObjects();    

        PageReference pageRef = Page.MMR_FF_Income;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', testable.log.id);
          
        MMR_FF_Income ctl = new MMR_FF_Income();
        ctl.setup();
        ctl.Save();
    }
    
    static testmethod void Prev_Test()
    {
         zTest_MMR_FF_Income testable = new zTest_MMR_FF_Income();
        testable.SetUpObjects();    

        PageReference pageRef = Page.MMR_FF_Income;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', testable.log.id);
          
        MMR_FF_Income ctl = new MMR_FF_Income();
        ctl.setup();
        ctl.Prev();
    }
    
    static testmethod void Next_Test()
    {
         zTest_MMR_FF_Income testable = new zTest_MMR_FF_Income();
        testable.SetUpObjects();    

        PageReference pageRef = Page.MMR_FF_Income;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', testable.log.id);
          
        MMR_FF_Income ctl = new MMR_FF_Income();
        ctl.setup();
        ctl.Next();
    }


    public void SetUpObjects()
    {
        z_DirectorHelper dHelp = new z_DirectorHelper();
        dHelp.AIPEvent();
        dHelp.ApplicationEvent();
        director = dHelp.Build();

        pHelp = new z_ProductHelper();        
        pHelp.Director(director.id);
        IBB_Product_Set__c prod  = pHelp.Build();


        //List<SOQLQuery__c> sql = [select id from SOQLQuery__c];
        //delete sql;
        
        z_MMRQuerySettings.CreateAll();
                
        z_OpportunityHelper oHelp = new z_OpportunityHelper('Test','Test');
        oHelp.Director(director.id);
        Opp = oHelp.build();  
        //Opp.interested_in__c = 'Test';              
        //update opp;        
        
        event= dHelp.Event;        
        ex  = new HPP_extended_opportunity__c ();
        ex.Opportunity__c = opp.id;
        insert ex;
                       
        log = new EventLog__c();
        log.Event__c = dHelp.Event.id;
        log.Opportunity__c = opp.id;
        log.EventStatus__c = 'Open';
        insert log;
    }

}