eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>CustomPageLocation__c</fullName>
        <label>CustomPageLocation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/EventLog__c.object
<CustomObject>
    <fields>
        <fullName>EventStatus__c</fullName>
        <label>EventStatus</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EventLog</label>
    <nameField>
        <label>EventLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Document PPDG/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>CAA_Rebuild__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CAA Rebuild</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/classes/CAA_Continue_Controller.cls
public class CAA_Continue_Controller
{
    private String ID = ApexPages.currentPage().getParameters().get('id');
    private String ExtID = ApexPages.currentPage().getParameters().get('extid');
    
    public Boolean IsOldCAA {get;set;}

    public PageReference Setup()
    {
        String oppId;
            
        if(string.IsNotBlank(ExtID ))
        {
            String decrypt = CAA_Helper.DecryptData(ExtID );   
            if(decrypt == null) throw new CAA_Helper.MyException('decryption failed');
            oppId = decrypt;
        }
        
        
        
            
        if(!CAA_Helper.IsGuestUser() && string.IsNotBlank(ID))
            oppId = ID;
            
        if(oppId == null) throw new CAA_Helper.MyException('no opp');
        
        List<Opportunity> opp = [select id, caa_rebuild__c from opportunity where id=:oppId];
        
        if(opp.size() != 1) throw new CAA_Helper.MyException('can\'t find opportunity');
                   
        IsOldCAA = !opp[0].caa_rebuild__c ;
        //if(IsOldCAA) return null;           
                   
                   
        //find next event
        List<EventLog__c> openEvents = [select id, Event__r.CustomPageLocation__c
                                         from eventlog__c where EventStatus__c='open' and Opportunity__c=:opp[0].id
                                         order by createddate limit  1];
                                         
        if(openEvents.size() == 1)
        {
            String url = openEvents[0].Event__r.CustomPageLocation__c;
            if(CAA_Helper.IsGuestUser())
            {
                url += '?extid=' + CAA_Helper.EncryptData(string.valueof(openEvents[0].id));
            }
            else
            {
                url+= '?id=' + openEvents[0].id;
            }
        
            return new PageReference(url);
        }  
        else
        {
            //throw new CAA_Helper.MyException('no events');
        }                              
            
        return null;
    }
}