eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/Event__c.object
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/EventLog__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>EventLogs</relationshipLabel>
        <relationshipName>EventLogs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>EventLog</label>
    <nameField>
        <label>EventLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EventLogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Document PPDG/src/classes/BaseEventController_test.cls
@isTest
public class BaseEventController_test{

    static testMethod void testMethodPostive(){
        BaseEventController bec=new BaseEventController();
        Event__c ev=new Event__c();
        ev.Name='Event test';
        insert ev;
        /*RecordType rt=new RecordType();
        rt.name='Liabilities Opportunities';
        insert rt;*/
        Account act=new Account();
        act.RecordTypeId = Schema.sObjectType.Account.getRecordTypeInfosByName().get('Prospect/Customer').getRecordTypeId();
        act.LastName='zensar';
        insert act;
        opportunity opp=new opportunity();
        opp.RecordTypeId = Schema.sObjectType.Opportunity.getRecordTypeInfosByName().get('Liabilities Opportunities').getRecordTypeId();
        opp.Name='Test opportunity';
        opp.Accountid=act.id;
        opp.StageName='test';
        opp.CloseDate=date.today();
        insert opp;
        EventLog__c el=new EventLog__c();
        el.Name='Event log Test';
        el.Event__c=ev.id;
        el.Opportunity__c=opp.id;
          test.startTest();
        insert el;
        bec.LoadEvent();
          test.stopTest();
    }
    
}