Document PPDG/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_of_nationality__c</fullName>
        <label>Country of nationality</label>
        <picklist>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Home_Telephone_No__c</fullName>
        <label>Primary contact number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Web_Form_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Form Data</label>
        <referenceTo>Web_Form_Data__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agreed_Purchase_Price__c</fullName>
        <label>Agreed Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Finance_Required__c</fullName>
        <label>Finance Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>GA_Campaign_Medium__c</fullName>
        <label>GA Campaign Medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GA_Campaign_Source__c</fullName>
        <label>GA Campaign Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Have_you_sourced_a_property__c</fullName>
        <label>Have you sourced a property</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>How_much_finance_do_you_require__c</fullName>
        <label>How much finance do you require?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Payment_Amount__c</fullName>
        <label>Initial deposit (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>Home Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTL Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Plan Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP BTL (future)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premier Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFA/Wealth Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discretionary Portfolio Service (DPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy-to-Let (BTL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy To Let (Rent Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety Deposit Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX Savings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Liabilities_eligibility_comments__c</fullName>
        <label>Liabilities eligibility comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Property_Value__c</fullName>
        <label>Property Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_FTV__c</fullName>
        <label>Proposed FTV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Web_Form_Data__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Web Form Data</label>
        <referenceTo>Web_Form_Data__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Will_minimum_charges_be_maintained__c</fullName>
        <label>Will minimum charges be maintained</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Private_Eligibility</fullName>
        <active>true</active>
        <businessProcess>Liabilities Sales Process</businessProcess>
        <label>Private Eligibility</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/objects/Web_Form_Data__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>GA_Campaign_Medium__c</fullName>
        <label>GA Campaign Medium</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GA_Campaign_Source__c</fullName>
        <label>GA Campaign Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Web Form Data</label>
    <nameField>
        <displayFormat>WForm-{00000}</displayFormat>
        <label>Web Form Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Web Form Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Document PPDG/src/classes/Private_Eligibility.cls
/* Start Code - C0732 */
public class Private_Eligibility
{
    public static List<ID> CreateCustomer(CAA_Data.PrivateCustomerEligibility data)
    {
        system.debug('Data:' + data);
        //return null;   
        
        Opportunity opp = new Opportunity();
        //Opportunity fields
        opp.CampaignId = data.Campaign;
        opp.Interested_in__c = data.InterestedIn;
        opp.Liabilities_eligibility_comments__c = data.Comments;
        opp.GA_Campaign_Source__c = data.Source;
        opp.GA_Campaign_Medium__c = data.Medium;
        opp.StageName ='Eligibility Completed';
        opp.Name = 'Eligibility';
        opp.CloseDate = Date.today();
        opp.Have_you_sourced_a_property__c = data.SourceProperty;
        opp.Property_Address__c = data.PropertyAddress;
        opp.Agreed_Purchase_Price__c = data.AgreedPurchasePrice;
        opp.Property_Value__c  = data.PropertyPrice;
        opp.How_much_finance_do_you_require__c = data.FinanceRequired;
        opp.Finance_Required__c  = data.MaximumFinanceRequired;
        opp.Proposed_FTV__c = data.ProposedFTV;
        opp.Will_minimum_charges_be_maintained__c = data.CustomerPayAccountCharges;
        opp.Initial_Payment_Amount__c = data.InitialDeposit;
        opp.Size__c = data.Size;
        
        
        
        
        RecordType rec = [select id,name from recordtype where developername=:'Private_Eligibility'];
        opp.recordtypeid = rec.id;
        
        if(string.isBlank(data.AccountId))
        {
            Account acc = new Account();        
            
            //Account fields
            acc.FirstName = data.FirstName;
            acc.LastName = data.LastName;        
           // acc.BillingPostalCode = data.Postcode;
            acc.Home_Telephone_No__c = data.PreferedContact;
            acc.PersonEmail = data.Email;
           // acc.Date_Of_Birth__c = data.DOB.Value; 
            acc.Salutation = data.Salutation;
            acc.Country_of_nationality__c = data.NationalityofCountry;
            acc.Country_of_Residence__c = data.CountryofResidence;
            insert acc;       
            opp.AccountId = acc.id;
        }
        else
        {
            opp.AccountId = data.accountId;
        }
        
        if(data.WebFormDataId!=''){
            opp.Web_Form_Data__c = data.WebFormDataId;
        }
        
        insert opp; 
        system.debug('opportunity details********' +opp);  
        
        system.debug('opp name*********' +opp.Name);      
        
        return new List<ID>{opp.AccountId,opp.Id};        
    }
}