Document PPDG/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>EBS_ID__c</fullName>
        <externalId>true</externalId>
        <label>EBS ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/objects/Card__c.object
<CustomObject>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electron</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maestro</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard Debit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Card</label>
    <nameField>
        <label>Card Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Document PPDG/src/objects/HPP_extended_opportunity__c.object
<CustomObject>
    <fields>
        <fullName>AdminFeeReceived__c</fullName>
        <label>Admin Fee Received</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>AdminFeeValue__c</fullName>
        <label>AdminFeeValue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Admin_Fee_Received_Full__c</fullName>
        <label>Admin Fee Received Full</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Date_admin_fee_paid__c</fullName>
        <description>For use with credit risk reporting</description>
        <label>Date admin fee paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_valuation_fee_paid__c</fullName>
        <label>Date valuation fee paid</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>HPP extended opportunities</relationshipLabel>
        <relationshipName>HPP_extended_opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Other_payment_account_no__c</fullName>
        <label>Other payment account no</label>
        <length>14</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_payment_method__c</fullName>
        <label>Other payment method</label>
        <picklist>
            <picklistValues>
                <fullName>Internal Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>External Transfer</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other payment method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_confirmed_by_other_method__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Payment confirmed by other method</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_none_comments__c</fullName>
        <label>Payment none comments</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ValuationFeeReceived__c</fullName>
        <label>ValuationFeeReceived</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ValuationPrice__c</fullName>
        <formula>Valuation_Table__r.Price_of_valuation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valuation Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ValuationType__c</fullName>
        <formula>TEXT( Valuation_Table__r.Type_of_valuation__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valuation Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valuation_fee_amount__c</fullName>
        <label>Valuation fee amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>HPP extended opportunity</label>
    <nameField>
        <displayFormat>HPPEO{0000}</displayFormat>
        <label>HPP extended opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HPP extended opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

eclipse-workspace/padmini/AlRayan/Zensar Sandbox Full Components/src/objects/IBB_Product__c.object
<CustomObject>
    <fields>
        <fullName>Valuation_Contribution_Amount__c</fullName>
        <label>Valuation Contribution Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valuation_Type__c</fullName>
        <label>Valuation Type</label>
        <picklist>
            <picklistValues>
                <fullName>Waived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discounted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Valuation Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refunded</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Document PPDG/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>HPP_extended_opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HPP extended opportunity</label>
        <referenceTo>HPP_extended_opportunity__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IBB_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>IBB_Product__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Initial_Payment_Amount__c</fullName>
        <label>Initial deposit (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Valuation_Contribution_Amount__c</fullName>
        <formula>IBB_Product__r.Valuation_Contribution_Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Valuation Contribution Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valuation_Refund_Amount__c</fullName>
        <label>Valuation Refund Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/classes/HPPEventContactCustomerController.cls
/* ---------------------------------------------------------------------------------------------- */
/* C00096 2013-10-16    Cater for non card payments                                               */
/*                      Check Internal Transfer Account Exists                                    */
/*                      No sort code displayed / captured                                         */
/*                      CHeck and do something with AJE errors                                    */
/* ---------------------------------------------------------------------------------------------- */
/* C00187 2014-04-02    Internal payments none doesn't save                                       */
/* ---------------------------------------------------------------------------------------------- */


public class HPPEventContactCustomerController extends HPPBaseEventController 
{
    public String BillingStreet {get;set;}
    public String BillingCity {get;set;}
    public String BillingCounty {get;set;}
    public String BillingPostCode {get;set;}
    public String BillingCountry {get;set;}
    public String ExternalComments {get;set;}
    public String NoneComments {get;set;}
    public Decimal ValuationContribution {get;set;}
    public static Decimal TotalValuationLeftToPay {get;set;}

	//C0638
	public String CaseTypeSelected {get;set;}
    public RecordType recTypeCase 
    {
        get 
        {
            if (recTypeCase == null){            
                recTypeCase = [select id from recordType where  sobjectType='case' and DeveloperName = 'Payments_Processing' limit 1];
            }
            return recTypeCase ;
        }
        set;
	}

		private static ID caseQueueID{
		get
		{
			List<QueueSobject> queues =  [SELECT QueueId
                                           FROM   QueueSobject
                                           WHERE  Queue.Name = 'Payments' LIMIT 1];                 
            if(queues.size()>0)
			{
				return queues[0].QueueId;
			}
			else
			{
				return null;
			}
		}
		set;
	}
    //
    /** This switch handles whether the CVC Security Code will be stored in the Database, 
     * or if a manual entry will be required each time. **/
    private final static Boolean REQUIRE_MANUAL_SECURITY_CODE_ENTRY = false;
    public Boolean PaymentTaken
    {
        get
        {
            return (String.isNotBlank(exOpp.ValuationFeeReceived__c) && exOpp.ValuationFeeReceived__c == 'Yes');
        }
    }   
    
    public HPPEventContactCustomerController() 
    {    
        CardData = new List<HPP_Data.CardData>();
      
        for(Card__c c : stSecureTrading_Cards.getSecureTradingCards(Acc.Id,Acc.PersonContactId))
        {
          HPP_Data.CardData card = new HPP_Data.CardData();
          card.CardId = c.id;
          card.CardNumber = c.name;
          card.CardType = c.Card_Type__c;
        
          CardData.add(card);
        }
    }
    
    public List<HPP_Data.CardData> CardData{get;set;}
    public String CardDataJson 
    {
        get{
            return Json.serialize(CardData);
        }
    }
    
    public String InternalAccounts
    {
        get
        {
            return Json.Serialize(HPPHelper.InternalAccounts(Acc.EBS_ID__c));        
        }       
    }

        
    @RemoteAction
    public static HPP_Data.GenericResponse TakeOtherPayment(ID oppID, HPP_Data.TakeOtherPaymentData data)
    {
        HPP_Data.TakePaymentResponse response = new HPP_Data.TakePaymentResponse ();
        
        Opportunity opp = [select id,name from opportunity where id=:OppId]; 
        HPP_extended_opportunity__c exOpp = [select id,name,ValuationFeeReceived__c,Admin_Fee_Received_Full__c,AdminFeeReceived__c,AdminFeeValue__c,Payment_Method__c,Date_admin_fee_paid__c,ValuationPrice__c,ValuationType__c  
                                          from HPP_extended_opportunity__c where opportunity__c =: OppId];
        
        Exopp.Payment_confirmed_by_other_method__c = data.ConfirmedOther;           
        if(string.isNotBlank(Exopp.ValuationFeeReceived__c) && Exopp.ValuationFeeReceived__c.equalsIgnoreCase('Yes'))
        {
            response.Errors.add('Payment has already been taken');        
            return response;
        }
        
        exOpp.Payment_Method__c = data.Method;
        exOpp.Payment_none_comments__c = data.NoneComments;
        exOpp.Other_payment_method__c = data.OtherPaymentMethod;
        exOpp.Payment_confirmed_by_other_method__c = false;
        
        HPPFinanceData.OverridePaymentMethod = data.Method.equalsIgnoreCase('Other') ? 'Other payment method' : data.Method;
        HPPFinanceData.OverrideOtherPaymentMethod = data.OtherPaymentMethod;
        
        
        if (data.Method.equalsIgnoreCase('Other') && data.OtherPaymentMethod.equalsIgnoreCase('Internal Transfer'))
        {
            if (string.isBlank(data.InternalAccount))
            {         
                response.Errors.add('No internal account number has been specified.');        
                return response;
            }
            else
            {
                exOpp.Other_payment_account_no__c = data.InternalAccount;
                HPPOpportunityMiddlewareMethods.OverrideInternalAccountPayment = data.InternalAccount;
            }
        }
        else if (data.Method.equalsIgnoreCase('None'))
        {
            exOpp.Payment_confirmed_by_other_method__c = true;
        }
        
        Actions.ActionAddJournalEntryValuation journalEntry = new Actions.ActionAddJournalEntryValuation();
        
        IBBEvents.CompleteEventArgs args;
        Boolean AJESuccess = true;
        if(!Data.Method.equalsIgnoreCase('None'))
        {    
            args = journalEntry.RunAction(OppId);
            AJESuccess = args.ReturnValue.equalsIgnoreCase ('SUCCESS');
        } 
       
        if (AJESuccess)
        {
            response.PaymentOk = true;
            exOpp.ValuationFeeReceived__c = 'Yes';
            //exOpp.Valuation_fee_amount__c = exOpp.ValuationPrice__c;
            exOpp.Valuation_fee_amount__c = TotalValuationLeftToPay;
            exOpp.Date_valuation_fee_paid__c = system.today();
            update exOpp;            
            response.AJEOk = true;
            response.Success = true;
        }
        else
        {
            response.Errors.add('The transaction has failed in EBS. ' + args.ErrorMessage);              
        }

        return response;    
    }    
    
    @RemoteAction 
    public static HPP_Data.TakePaymentResponse TakePayment(HPP_Data.TakePaymentData data)
    {
        HPP_Data.TakePaymentResponse response = new HPP_Data.TakePaymentResponse ();
        
        Opportunity opp = [select id,name, Initial_Payment_Amount__c from opportunity where id=:data.OppId]; 
        HPP_extended_opportunity__c exOpp = [select id,name,ValuationFeeReceived__c,Admin_Fee_Received_Full__c,AdminFeeReceived__c,AdminFeeValue__c,Payment_Method__c ,Date_admin_fee_paid__c,ValuationPrice__c,ValuationType__c
                                          from HPP_extended_opportunity__c where opportunity__c =: data.OppId];    
        
        if(string.isNotBlank(Exopp.ValuationFeeReceived__c) && Exopp.ValuationFeeReceived__c.equalsIgnoreCase('Yes'))
        {
            response.Errors.add('Payment has already been taken');        
            return response;
        }
        
        Card__c selectedCard = stSecureTrading_Cards.selectCard(data.SelectedCardId);
        exOpp.Payment_Method__c = 'Card';
        HPPFinanceData.OverridePaymentMethod = 'Card';

        //response = stSecureTrading_TakePayment.TakeInternalCardPayment(exOpp.ValuationPrice__c, selectedCard, opp, response,new Actions.ActionAddJournalEntryValuation());
        response = stSecureTrading_TakePayment.TakeInternalCardPayment(opp.Initial_Payment_Amount__c, selectedCard, opp, response,new Actions.ActionAddJournalEntryValuation());
        
        if(!response.success) return response;
        
        //If the payment was taken successfully we update the status on the opportunity, even if the AJE failed
        if(response.PaymentOk)
        {
            exOpp.ValuationFeeReceived__c = 'Yes';
            //exOpp.Valuation_fee_amount__c = exOpp.ValuationPrice__c;
            exOpp.Valuation_fee_amount__c = TotalValuationLeftToPay;
            exOpp.Date_valuation_fee_paid__c = system.today();
            update exOpp;
        }        
        return response;        
    }
    
    @RemoteAction
    public static HPP_Data.GenericResponse CompleteTheEvent(ID oppID, String eventLogId)
    {
        HPP_Data.GenericResponse response = new HPP_Data.GenericResponse();
        Boolean completeEvent = true;        
        
        if(!completeEvent) return response;
        
        String newEventUrl = HPPHelper.CompleteEvent(eventLogId);    
        if(!string.isBlank(newEventUrl))
        {
            response.Success = true;
            response.Url =  newEventUrl;
        }
        return response;
    }
    
    @RemoteAction
    public static HPP_Data.SaveNewCardResponse SaveCard(HPP_Data.CardData card)
    {
        return stSecureTrading_Cards.SaveCard(card,REQUIRE_MANUAL_SECURITY_CODE_ENTRY); 
    }
  
    @RemoteAction
    public static EncryptedCard selectEncryptedCard(String cardID) 
    {
        return stSecureTrading_Cards.selectEncryptedCard(cardID);
    }
    
	//C0638
	public PageReference CreateCase()
	{
		Case newcase = new Case();
		newcase.RecordTypeId = recTypeCase.Id;
		newcase.Origin = 'Salesforce';
		newcase.Category_revised__c = 'Suspended Transaction';
		newcase.Priority = 'Meduim';
		newcase.Referral_Decision__c = CaseTypeSelected;
		newcase.Opportunity__c = Opp.Id;
		newcase.Location_of_submitter__c = 'Head Office';
		newcase.Status = 'Awaiting Allocation';
		ID qID = caseQueueID;
		if(qID!=null)
		{
			newcase.OwnerId = qID;
		}

		if (CaseTypeSelected == 'Suspended-Cancel')
        {
            newcase.Sub_category_revised__c= 'Cancel Transaction';
			newcase.Subject = 'Suspended card payment for amount ' + exOpp.ValuationPrice__c + ' should be cancelled';
        }
		else if (CaseTypeSelected == 'Suspended-Release')
        {
		    newcase.Sub_category_revised__c = 'Release Transaction';
			newcase.Subject = 'Suspended card payment for amount ' + exOpp.ValuationPrice__c + ' should be released';
		}

		insert newcase;
		return null;
	}

    public PageReference autoRun() {
        system.debug('HPPEventContactCustomerController.autoRun Entry');
        IBBDependentObjectFactory.CreateAJEStubsValuation(opp);
        
        
        //Check string values for quote characters
        
        if(exOpp.Payment_none_comments__c != null)
        {
            NoneComments = exOpp.Payment_none_comments__c.replace('\'','\\\'');
            ExternalComments = exOpp.Payment_none_comments__c.replace('\'','\\\'');
        }    
        
        if(Acc.BillingStreet != null)
            BillingStreet = Acc.BillingStreet.replace('\'','\\\'');
        if(Acc.BillingCity != null)
            BillingCity = Acc.BillingCity.replace('\'','\\\'');
        if(Acc.BillingState != null)
            BillingCounty = Acc.BillingState.replace('\'','\\\'');
        if(Acc.BillingPostalCode != null)
            BillingPostCode = Acc.BillingPostalCode.replace('\'','\\\'');
        if(Acc.BillingCountry != null)
            BillingCountry = Acc.BillingCountry.replace('\'','\\\'');
        
        
        // Logic to calculate Valuation fields
        Opportunity baseOpp = [SELECT Id, Initial_Payment_Amount__c, IBB_Product__r.Valuation_Type__c, IBB_Product__r.Valuation_Contribution_Amount__c, Valuation_Refund_Amount__c FROM Opportunity WHERE Id=:exOpp.Opportunity__c];

        if (baseOpp.IBB_Product__r.Valuation_Type__c == 'Waivered') {
            ValuationContribution = exOpp.ValuationPrice__c;
            TotalValuationLeftToPay = 0.0;
        }
        else if (baseOpp.IBB_Product__r.Valuation_Type__c == 'Discounted') {
            ValuationContribution = baseOpp.IBB_Product__r.Valuation_Contribution_Amount__c;
            TotalValuationLeftToPay = exOpp.ValuationPrice__c - ValuationContribution;
            if (TotalValuationLeftToPay < 0) { TotalValuationLeftToPay = 0.0; } // Default negative values to 0
        }
        else {
            ValuationContribution = baseOpp.IBB_Product__r.Valuation_Contribution_Amount__c;
            TotalValuationLeftToPay = exOpp.ValuationPrice__c;
        }

        baseOpp.Valuation_Refund_Amount__c = 0.0;
        if (baseOpp.IBB_Product__r.Valuation_Type__c == 'Refunded') {
            if (exOpp.ValuationPrice__c >= baseOpp.IBB_Product__r.Valuation_Contribution_Amount__c) {
               baseOpp.Valuation_Refund_Amount__c = baseOpp.IBB_Product__r.Valuation_Contribution_Amount__c;
            }
            else {
                baseOpp.Valuation_Refund_Amount__c = exOpp.ValuationPrice__c;
            }
        }

        if (!PaymentTaken) {
            // Update Opportunity
            baseOpp.Initial_Payment_Amount__c = TotalValuationLeftToPay;
            update baseOpp;
        }

        return null;
    }
}