Document PPDG/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Country_of_Residence__c</fullName>
        <label>Country of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country_of_nationality__c</fullName>
        <label>Country of nationality</label>
        <picklist>
            <picklistValues>
                <fullName>United Kingdom</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua And Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia-Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Home_Telephone_No__c</fullName>
        <label>Primary contact number</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agreed_Purchase_Price__c</fullName>
        <label>Agreed Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Finance_Required__c</fullName>
        <label>Finance Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Have_you_sourced_a_property__c</fullName>
        <label>Have you sourced a property</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>How_much_finance_do_you_require__c</fullName>
        <label>How much finance do you require?</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Initial_Payment_Amount__c</fullName>
        <label>Initial deposit (£)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>Home Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTL Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Plan Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP BTL (future)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premier Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFA/Wealth Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discretionary Portfolio Service (DPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy-to-Let (BTL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy To Let (Rent Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety Deposit Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX Savings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Liabilities_eligibility_comments__c</fullName>
        <label>Liabilities eligibility comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Property_Value__c</fullName>
        <label>Property Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Proposed_FTV__c</fullName>
        <label>Proposed FTV</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <label>Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Will_minimum_charges_be_maintained__c</fullName>
        <label>Will minimum charges be maintained</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Private_Eligibility</fullName>
        <active>true</active>
        <businessProcess>Liabilities Sales Process</businessProcess>
        <label>Private Eligibility</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/classes/TestPrivate_Eligibility.cls
/* Start Code - C0732 */
@isTest
public class TestPrivate_Eligibility
{
    static testMethod void privateTest()
    {
    
    List<Account> acc = new List<Account>();
    Account a = new Account();
    a.FirstName = 'test name';
    a.LastName  = ' test lastname';
    a.Home_Telephone_No__c = '898509340';
    a.PersonEmail = 'test@demo.com';
    a.Salutation = 'MR';
    a.Country_of_nationality__c = 'United Kingdom';
    a.Country_of_Residence__c  = 'United Kingdom';
    acc.add(a);
    insert acc;
    
    List<Campaign> cam = new List<Campaign>();
    Campaign c = new Campaign();
    c.Name = 'Test campaign';
    cam.add(c);
    insert cam;
    
    
    List<Opportunity> opp = new List<Opportunity>();
    RecordType rec = [select id,name from recordtype where developername=:'Private_Eligibility'];
    Opportunity o = new Opportunity();
    o.recordtypeid = rec.id;
    o.Interested_in__c = 'Home Purchase Plan Premier';
    o.AccountId = acc[0].Id;
    o.CampaignId = cam[0].Id;
    o.StageName = 'Eligibility Completed';
    o.CloseDate = System.Today();
    o.Liabilities_eligibility_comments__c  = 'test comments';
    o.Name = 'test opp';
    o.Have_you_sourced_a_property__c = 'Yes';
    o.Property_Address__c = 'test address';
    o.Agreed_Purchase_Price__c = 20000;
    o.Property_Value__c  = 20000;
    o.How_much_finance_do_you_require__c = 10000;
    o.Finance_Required__c  = 1000;
    o.Proposed_FTV__c = '7';
    o.Will_minimum_charges_be_maintained__c = 'Yes';
    o.Initial_Payment_Amount__c = 100;
    o.Size__c = 9;
    opp.add(o);
    insert opp;
    
   
    CAA_Data cd = new CAA_Data();
    CAA_Data.PrivateCustomerEligibility cp = new CAA_Data.PrivateCustomerEligibility();
    cp.LastName = 'test lastname';
   
    
    Private_Eligibility pe = new Private_Eligibility();
    Private_Eligibility.CreateCustomer(cp);
    
       

}

}

/* End Code - C0732 */