Document PPDG/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Estimated_actual_monthly_rental_income__c</fullName>
        <description>What is the estimated/actual monthly rental income from the property?</description>
        <label>Estimated/actual monthly rental income?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Finance_Required__c</fullName>
        <label>Finance Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Interested_in__c</fullName>
        <label>Interested in</label>
        <picklist>
            <picklistValues>
                <fullName>Home Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BTL Purchase Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Plan Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Long Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Short Term Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Current Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial Property Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP BTL (future)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Premier Banking</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IFA/Wealth Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discretionary Portfolio Service (DPS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Premier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy-to-Let (BTL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HPP Buy To Let (Rent Only)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Purchase Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buy To Let Purchase Plan Scotland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safety Deposit Box</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FX Savings</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_Joint_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Joint Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_type__c</fullName>
        <label>Property type</label>
        <picklist>
            <picklistValues>
                <fullName>terrace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>semi-detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>bungalow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flat</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>studio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>maisonette</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Council property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ex council property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing association</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Residential</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mixed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchase_price_market_value__c</fullName>
        <label>Purchase Price/Market Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Purpose_of_Finance__c</fullName>
        <label>Purpose of Finance</label>
        <picklist>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner Moving House</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinancing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equity Release</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase (BTL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance (BTL)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shared ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Right to buy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Key worker scheme</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Term_of_Finance__c</fullName>
        <label>Term of Finance</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Document PPDG/src/classes/zTest_MMR_Calculator.cls
@isTest
private class zTest_MMR_Calculator {

	@isTest
	private static void testMMRCalculator_HPP()
	{
		// Assign values
		Opportunity o = new Opportunity();
		o.Is_Joint_Application__c = false;
		o.Finance_Required__c=300000;
		o.Purchase_price_market_value__c=400000;
		o.Term_of_Finance__c=25;
		o.Estimated_actual_monthly_rental_income__c=2000;
		o.Interested_in__c='Home Purchase Plan';
		o.Purpose_of_Finance__c='New Purchase';
		o.Property_type__c='Private Property';
		Decimal ExpectedAmortisedRepayment = 1501.87;
		Decimal ExpectedRentOnlyRepayment = 875;
		
		// Actions
		MMR_Calculator mmrCalc = new MMR_Calculator(o);
		mmrCalc.RateToUse = 3.5;
		mmrCalc.CalculateMonthlyRepayment(false);

		Decimal ActualAmortisedRepayment = mmrCalc.MonthlyRepaymentAmortised.setScale(2);
		Decimal ActualRentOnlyRepayment = mmrCalc.MonthlyRepaymentRentOnly.setScale(2);

		// Assert
		system.assertEquals(ExpectedAmortisedRepayment,ActualAmortisedRepayment);
		system.assertEquals(ExpectedRentOnlyRepayment,ActualRentOnlyRepayment);

		// Test NULLs
		mmrCalc.RateToUse=null;
		mmrCalc.CalculateMonthlyRepayment(false);

		// Assert
		system.assertEquals(null,mmrCalc.MonthlyRepaymentAmortised);
		system.assertEquals(null,mmrCalc.MonthlyRepaymentRentOnly);


	}

	@isTest
	private static void testMMRCalculator_BTL()
	{
		// Assign values
		Opportunity o = new Opportunity();
		o.Is_Joint_Application__c = false;
		o.Finance_Required__c=300000;
		o.Purchase_price_market_value__c=400000;
		o.Term_of_Finance__c=25;
		o.Estimated_actual_monthly_rental_income__c=2000;
		o.Interested_in__c='Buy To Let Purchase Plan';
		o.Purpose_of_Finance__c='New Purchase';
		o.Property_type__c='Private Property';

		
		// Actions
		MMR_Calculator mmrCalc = new MMR_Calculator(o);
		mmrCalc.UseTestBTLParams= true;
		mmrCalc.ExpectedRent=1000;
		mmrCalc.CalculateMonthlyRepayment(true);

		Double GrossRentalIncome = mmrCalc.GrossRentalIncome;
		Double NetRentalIncome = mmrCalc.NetRentalIncome;
		Double RentCoverageRatio = mmrCalc.RentCoverageRatio;

		// Assert
		// Can't test the calculator properly without rewriting it in the Assign/Action stages, so for now just ensure values are present and correct
		// to get further coverage
		system.assertEquals(GrossRentalIncome,NetRentalIncome*RentCoverageRatio);
		system.assertEquals(mmrCalc.PRACoverage,73);

	}
}